### PR TITLE
First intregration of SYMM Backend for AudioDownload only

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Kimmax** [comment]
@di48l069 This would eliminate the problem, yes, although you would have to use the GPL License as well.

**Comment by di48l069** [comment]
@Kimmax Project is now public

**Comment by di48l069** [comment]
how would i apply this license?

**Comment by Kimmax** [comment]
@di48l069 Changed it for you. Nothing critical, we have just to match.

**Comment by di48l069** [comment]
No problem man will you continue your beautiful work? haha

**Comment by Kimmax** [comment]
sure

**Comment by di48l069** [comment]
Thanks man :+1:

**Comment by Kimmax** [comment]
Your workflow has changed.
To continue working on the new base you'll have to do the following:
```
git clone https://github.com/Kimmax/SYMM.git
cd SYMM
git submodule init
git submodule update
```
You will have than all required files to build. Go to _/src/SYMM Frontend Console_ and work from there as you would in your current project folder (git commit, push etc. this is your repo). To make things build you'll have to fire op `Flash-dl.sln` and in the Projectexplorer add the following existing projects: _/lib//YoutubeExtractor/YoutubeExtractor/YoutubeExtractor/YoutubeExtractor.csproj_ and _/src/SYMM Backend/SYMM Backend.csproj_ Then right click on the _Flash-dl_ project and add *project* references to both of them.  
Add Youtubeextractor to the project first or the backend will complain. Hit build and some nugets should restore -> you're good to go.  
When you don't do work related to the implementation witch to master before please (`git checkout master` (again: you have to do this in _/src/SYMM Frontend Console_).

**Comment by di48l069** [comment]
@Kimmax sorry man kinda confused new to this github command i use the client

**Pull request merged**
